apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
bootstrapTokens:
    - groups:
          - system:bootstrappers:kubeadm:default-node-token
      token: abcdef.0123456789abcdef
      ttl: 24h0m0s
      usages:
          - signing
          - authentication
localAPIEndpoint:
    advertiseAddress: 10.20.0.11 # master1 ip
    bindPort: 6443
nodeRegistration:
    criSocket: /var/run/dockershim.sock
    name: master1
    taints:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master

---
apiVersion: kubeadm.k8s.io/v1beta2
kubernetesVersion: v1.22.8
kind: ClusterConfiguration
clusterName: kubernetes
controlPlaneEndpoint: 10.20.0.10:6443 # proxy ip
apiServer:
    timeoutForControlPlane: 4m0s
    extraArgs:
        authorization-mode: Node,RBAC
        service-node-port-range: 80-32767
        max-requests-inflight: "1000"
        max-mutating-requests-inflight: "500"        
        default-watch-cache-size: "500"
        watch-cache-sizes: "persistentvolumeclaims#1000,persistentvolumes#1000"
certificatesDir: /etc/kubernetes/pki
networking:
    dnsDomain: cluster.local
    serviceSubnet: 10.20.50.0/20
    podSubnet: 192.168.0.0/16
controllerManager: {}
dns:
    type: CoreDNS
etcd:
    local:
        dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io

scheduler: {}
